name: Build and Test on Multiple JDKs

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    name: Test with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install npm dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Remove any existing JAR
        run: rm -f bin/lt-filter.jar

      - name: Build with Maven
        run: mvn package

      - name: Verify JAR was built
        run: ls -la bin/lt-filter.jar

      - name: Run basic functionality tests
        run: cd tests && ./test-basic.sh

      - name: Run stdin functionality tests
        run: cd tests && ./test-stdin.sh

      - name: Run Node.js wrapper tests
        run: cd tests && ./test-node-wrapper.sh

      - name: Run disable-rules functionality tests
        run: cd tests && ./test-disable-rules.sh

      - name: Run rule-names functionality tests
        run: cd tests && ./test-rule-names.sh

      - name: Run server functionality tests
        run: cd tests && ./test-server.sh
